[package]
name = "fastn-package"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
fastn-continuation.workspace = true
fastn-section.workspace = true
fastn-utils.workspace = true

[dev-dependencies]
fastn-utils = { workspace = true, features = ["test-utils"] }
indoc = { workspace = true }
