[package]
name = "fastn-section"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
arcstr.workspace = true
serde.workspace = true
serde_json.workspace = true
string-interner.workspace = true
id-arena.workspace = true
fastn-continuation.workspace = true
tracing.workspace = true
