[package]
name = "fastn-package"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
camino.workspace = true
fastn-issues.workspace = true
ftd.workspace = true
futures.workspace = true
rusqlite.workspace = true
serde.workspace = true
tokio.workspace = true
