[package]
name = "ftd-rt"
version = "0.1.0"
authors = ["Amit Upadhyay <amitu@fifthtry.com>"]
edition = "2018"
description = "ftd-rt: FifthTry Document Format parser at Run Time"
license = "MIT"
repository = "https://github.com/fifthtry/ftd"
homepage = "https://www.fifthtry.com/fifthtry/ftd/"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["realm"]
wasm = ["console_error_panic_hook", "wasm-bindgen", "web-sys"]
realm = []

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
serde_json = { version = "1" }

console_error_panic_hook = { version = "0.1.6", optional = true }
wasm-bindgen = { version = "0.2.74", optional = true, features = ["serde-serialize"] }

[dependencies.web-sys]
version = "0.3.51"
optional = true
features = [
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
]
