[package]
name = "fastn-unresolved"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
arcstr.workspace = true
fastn-builtins.workspace = true
fastn-package.workspace = true
fastn-continuation.workspace = true
fastn-resolved.workspace = true
fastn-section.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
