[package]
name = "fastn-utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
test-utils = ["arcstr", "thiserror", "fastn-continuation"]

[dependencies]
fastn-continuation = { workspace = true, optional = true }
fastn-section.workspace = true
arcstr = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
# indoc = { workspace = true, optional = true }
