[package]
name = "fastn"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
arcstr.workspace = true
async-trait.workspace = true
fastn-compiler.workspace = true
fastn-continuation = { workspace = true, features = ["async_provider"] }
fastn-package.workspace = true
fastn-router.workspace = true
fastn-runtime.workspace = true
fastn-section.workspace = true
fastn-unresolved.workspace = true
fastn-utils.workspace = true
http-body-util.workspace = true
hyper-util.workspace = true
hyper.workspace = true
ignore.workspace = true
serde_json.workspace = true
tokio.workspace = true
