[package]
name = "ftd"
version = "0.3.0"
description.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = []
native-rendering = ["taffy", "crossterm"]
# terminal = ["rink", "dioxus-native-core", "dioxus-native-core-macro", "dioxus-html", "futures", "tokio", "rustc-hash"]

[dependencies]
comrak.workspace = true
crossterm = { workspace = true, optional = true }
css-color-parser.workspace = true
#dioxus-html = { workspace = true, optional = true }
#dioxus-native-core = { workspace = true, optional = true }
#dioxus-native-core-macro = { workspace = true, optional = true }
format_num.workspace = true
ftd-p1.workspace = true
#futures = { workspace = true, optional = true }
include_dir.workspace = true
indoc.workspace = true
itertools.workspace = true
once_cell.workspace = true
regex.workspace = true
#rink = { workspace = true, optional = true }
#rustc-hash = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
slug.workspace = true
syntect.workspace = true
taffy = { workspace = true, optional = true }
thiserror.workspace = true
#tokio = { workspace = true, optional = true }
tracing.workspace = true
fastn-js.workspace = true
fastn-grammar.workspace = true
indexmap.workspace = true
colored.workspace = true

[dev-dependencies]
diffy.workspace = true
pretty_assertions.workspace = true
